In [1]:
# !pip install pandas
# !pip install SQLAlchemy
# !pip install psycopg2
# !pip install pyrefly

In [2]:
import pandas as pd
import sqlalchemy as sql

pd.set_option("display.max_rows", 28)
pd.set_option("display.max_columns", 50)

In [3]:
df: pd.DataFrame = pd.read_json("data/data2021/allotments2021.json")
df = pd.json_normalize(list(df.get("data")))
df

,college_code,college_name,district,college_type,branch_code,branch_name,oc_initial,oc_filled,bc_initial,bc_filled,bcm_initial,bcm_filled,mbc_initial,mbc_filled,sc_initial,sc_filled,sca_initial,sca_filled,st_initial,st_filled
0,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,BY,BIO MEDICAL ENGINEERING (SS),16,16,14,14,2,2,1,1,8,8,2,2,1,1
1,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CE,CIVIL ENGINEERING,16,16,14,14,2,2,1,1,8,8,2,2,1,1
2,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CM,COMPUTER SCIENCE AND ENGINEERING (SS),31,31,25,25,4,4,3,3,17,17,3,3,1,1
3,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CS,COMPUTER SCIENCE AND ENGINEERING,16,16,16,16,2,2,1,1,7,7,2,2,1,1
4,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,16,16,14,14,1,1,2,2,8,8,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2825,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,CE,CIVIL ENGINEERING,16,3,14,0,2,0,1,0,9,0,2,0,0,0
2826,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,CS,COMPUTER SCIENCE AND ENGINEERING,16,16,13,13,2,2,1,0,7,2,1,0,1,0
2827,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,16,10,14,0,2,0,1,0,7,0,2,0,1,0
2828,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,EE,ELECTRICAL AND ELECTRONICS ENGINEERING,8,5,6,0,1,0,1,0,4,0,1,0,0,0
2829,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,ME,MECHANICAL ENGINEERING,25,12,22,0,3,0,2,0,12,0,1,0,1,0

In [4]:
df.branch_code.unique()

<StringArray>
['BY', 'CE', 'CM', 'CS', 'EC', 'EE', 'EM', 'GI', 'IE', 'IM', 'MA', 'ME', 'MI',
 'MN', 'PT', 'XC', 'XM', 'AP', 'CH', 'CL', 'CR', 'FS', 'IB', 'IS', 'LE', 'PM',
 'PP', 'TX', 'AE', 'AU', 'EI', 'MF', 'PR', 'RP', 'IT', 'MT', 'AS', 'BS', 'CN',
 'ES', 'FY', 'IY', 'MS', 'MY', 'PN', 'PS', 'RA', 'TT', 'AT', 'EY', 'CW', 'MG',
 'PA', 'HT', 'CC', 'BT', 'PC', 'PH', 'AM', 'CF', 'CZ', 'MM', 'FD', 'AD', 'MZ',
 'AL', 'CB', 'CD', 'BM', 'MR', 'AG', 'RM', 'CO', 'PE', 'MD', 'MH', 'MU', 'AO',
 'FT', 'CJ', 'IC', 'CY', 'XS', 'PU', 'MC', 'SF', 'TC', 'TS', 'CT', 'SE', 'ET',
 'SC', 'PD', 'MO', 'SB', 'EN', 'BC', 'IN']
Length: 98, dtype: str

In [5]:
years = [2021,2022,2023,2024,2025]


df = pd.DataFrame()

df_list: list[pd.DataFrame] = []

for year in years:
    df = pd.read_json(f"data/data{year}/allotments{year}.json")
    df = pd.json_normalize(list(df.get("data")))
    df["year"] = year
    df_list.append(df)


df = pd.concat(df_list)
df.axes

[Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
        ...
        3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456],
       dtype='int64', length=16174),
 Index(['college_code', 'college_name', 'district', 'college_type',
        'branch_code', 'branch_name', 'oc_initial', 'oc_filled', 'bc_initial',
        'bc_filled', 'bcm_initial', 'bcm_filled', 'mbc_initial', 'mbc_filled',
        'sc_initial', 'sc_filled', 'sca_initial', 'sca_filled', 'st_initial',
        'st_filled', 'year'],
       dtype='str')]

In [6]:
counts = df.groupby(df.columns.tolist(), dropna=False).size()

print(counts[counts > 1])

Series([], dtype: int64)

In [7]:
# First taking the college data from it 

college_data : pd.DataFrame = df[["college_code","college_name","district","college_type"]]

In [8]:
college_data.drop_duplicates()

,college_code,college_name,district,college_type
0,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS
17,2,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS
28,4,"University Departments of Anna University, Che...",CHENGALPET,CEG DEPTS
39,1516,Thanthai Periyar Government Institute of Techn...,VELLORE,GOVERNMENT ENGG COLLEGES
44,2005,"Government College of Technology (Autonomous),...",COIMBATORE,GOVERNMENT ENGG COLLEGES
...,...,...,...,...
3250,5545,"G.T.N COLLEGE OF TECHNOLOGY, OLD KARUR ROAD, D...",DINDIGUL,SELF FINANCING COLLEGES TIER 3
3255,5546,"Jamal Mohamed College of Engineering, NH-45, T...",DINDIGUL,SELF FINANCING COLLEGES TIER 3
3293,5862,"RVS School of Engineering and Technology, (For...",DINDIGUL,SELF FINANCING COLLEGES TIER 3
3325,5907,Mohamed Sathak Engineering College (Autonomous...,RAMANATHAPURAM,SELF FINANCING COLLEGES TIER 3
3381,5914,Solamalai College of Engineering (Autonomous)...,MADURAI,SELF FINANCING COLLEGES TIER 3

In [9]:
#Data cleaning 

def remove_repeated_colleges(df : pd.DataFrame):
    df = df.drop_duplicates(subset=["counselling_code"], keep="last")
    return df

In [10]:
def find_financial_status(val : str) -> str:
    if(val == "CEG DEPTS"):
        return "GOVT"
    elif(val == "GOVERNMENT ENGG COLLEGES"):
        return "GOVT"
    elif(val == "GOVERNMENT AIDED COLLEGES"):
        return "AIDED"
    elif(val == "CENTRAL GOVERNMENT ENGG COLLEGES COLLEGES"):
        return "GOVT"
    elif(val == "UNIV CONSTITUENT COLLEGES"):
        return "GOVT"
    elif(val == "ANNAMALAI UNIV"):
        return "GOVT"
    elif(val == "SELF FINANCING COLLEGES TIER 3"):
        return "PRIVATE"
    elif(val == "SELF FINANCING COLLEGES TIER 2"):
        return "PRIVATE"
    elif(val == "SELF FINANCING COLLEGES TIER 1"):
        return "PRIVATE"


def find_college_tier(val : str) -> str:
    if(val == "CEG DEPTS"):
        return "CEG"
    elif(val == "GOVERNMENT ENGG COLLEGES"):
        return "GOVT"
    elif(val == "GOVERNMENT AIDED COLLEGES"):
        return "AIDED"
    elif(val == "CENTRAL GOVERNMENT ENGG COLLEGES COLLEGES"):
        return "CENT_GOVT"
    elif(val == "UNIV CONSTITUENT COLLEGES"):
        return "ANNA_UNIV"
    elif(val == "ANNAMALAI UNIV"):
        return "ANNAMALAI_UNIV"
    elif(val == "SELF FINANCING COLLEGES TIER 3"):
        return "TIER 3"
    elif(val == "SELF FINANCING COLLEGES TIER 2"):
        return "TIER 2"
    elif(val == "SELF FINANCING COLLEGES TIER 1"):
        return "TIER 1"





# Snippet to extract the data needed for the college for the college table in the schema
def extract_college_data(year : int) -> str:
    df = pd.read_json(f"data/data{year}/allotments{year}.json")
    df = pd.json_normalize(list(df.get("data")))
    college_data = df[["college_type","college_code","district","college_name"]]
    college_data.drop_duplicates(inplace=True)
    college_data.rename(columns={"college_type":"category"},inplace=True)
    college_data.rename(columns={"college_code":"counselling_code"},inplace=True)
    college_data.rename(columns={"college_name":"name"},inplace=True)
    college_data["financial_status"] = college_data["category"].apply(find_financial_status)
    college_data["tier"] = college_data["category"].apply(find_college_tier)
    return college_data



college_data = pd.DataFrame()


data: list[pd.DataFrame] = []

for year in years:
    data.append(extract_college_data(year))


college_data = pd.concat(data)
college_data.drop_duplicates(inplace=True)
    

college_data = remove_repeated_colleges(college_data)

In [11]:
college_data

,category,counselling_code,district,name,financial_status,tier
404,SELF FINANCING COLLEGES TIER 3,1158,CHENNAI,"International Maritime Academy, No.41, Jamin ...",PRIVATE,TIER 3
410,SELF FINANCING COLLEGES TIER 3,1205,KANCHEEPURAM,"Lord Venkateshwaraa Engineering College, Walaj...",PRIVATE,TIER 3
542,SELF FINANCING COLLEGES TIER 2,1231,THIRUVALLUR,"Panimalar Institute of Technology, Nazarethpet...",PRIVATE,TIER 2
887,SELF FINANCING COLLEGES TIER 3,1435,CHENGALPET,"Jagannath Institute of Technology, Thandalam ...",PRIVATE,TIER 3
924,SELF FINANCING COLLEGES TIER 3,1447,CHENNAI,"Jawahar Engineering College, Kaveri Rangan Nag...",PRIVATE,TIER 3
...,...,...,...,...,...,...
3250,SELF FINANCING COLLEGES TIER 3,5545,DINDIGUL,"G.T.N COLLEGE OF TECHNOLOGY, OLD KARUR ROAD, D...",PRIVATE,TIER 3
3255,SELF FINANCING COLLEGES TIER 3,5546,DINDIGUL,"Jamal Mohamed College of Engineering, NH-45, T...",PRIVATE,TIER 3
3293,SELF FINANCING COLLEGES TIER 3,5862,DINDIGUL,"RVS School of Engineering and Technology, (For...",PRIVATE,TIER 3
3325,SELF FINANCING COLLEGES TIER 3,5907,RAMANATHAPURAM,Mohamed Sathak Engineering College (Autonomous...,PRIVATE,TIER 3
3381,SELF FINANCING COLLEGES TIER 3,5914,MADURAI,Solamalai College of Engineering (Autonomous)...,PRIVATE,TIER 3

In [12]:
college_data = college_data.sort_values('counselling_code',ascending=True)

In [13]:
def push_college_data_to_table(college_data : pd.DataFrame) -> None:
    college_data.to_sql("college",con=engine,if_exists="append",index=False)

In [14]:
engine: pd.Engine = sql.create_engine("postgresql+psycopg2://tneaadmin:tneadb@localhost:5432/tneadb")

conn = sql.Connection(engine)

In [15]:
print(conn.exec_driver_sql("SELECT * FROM college").keys())

RMKeyView(['id', 'category', 'counselling_code', 'district', 'name', 'web_link', 'latitude', 'longitude', 'financial_status', 'tier'])

In [ ]:
# push_college_data_to_table(college_data)

In [17]:
college_data.reset_index(drop=True)
# college_data.drop(columns=["index"],inplace=True)
college_data.index = range(1, 467 + 1)

In [18]:
college_data

,category,counselling_code,district,name,financial_status,tier
1,CEG DEPTS,1,CHENNAI,University Departments of Anna University Che...,GOVT,CEG
2,CEG DEPTS,2,CHENNAI,University Departments of Anna University Che...,GOVT,CEG
3,CEG DEPTS,3,CHENNAI,School of Architecture and Planning Anna Univ...,GOVT,CEG
4,CEG DEPTS,4,CHENGALPET,University Departments of Anna University Che...,GOVT,CEG
5,ANNAMALAI UNIV,5,CUDDALORE,Annamalai University Faculty of Engineering an...,GOVT,ANNAMALAI_UNIV
...,...,...,...,...,...,...
463,SELF FINANCING COLLEGES TIER 3,5935,MADURAI,Fatima Michael College of Engineering and Tech...,PRIVATE,TIER 3
464,SELF FINANCING COLLEGES TIER 3,5942,MADURAI,"Ultra College of Engineering and Technology , ...",PRIVATE,TIER 3
465,SELF FINANCING COLLEGES TIER 1,5986,MADURAI,Velammal College of Engineering and Technology...,PRIVATE,TIER 1
466,SELF FINANCING COLLEGES TIER 3,5988,THENI,"Theni Kammavar Sangam College of Technology, T...",PRIVATE,TIER 3
467,SELF FINANCING COLLEGES TIER 3,5990,MADURAI,"Latha Mathavan Engineering College, Latha Math...",PRIVATE,TIER 3

In [19]:
college_data.axes

[RangeIndex(start=1, stop=468, step=1),
 Index(['category', 'counselling_code', 'district', 'name', 'financial_status',
        'tier'],
       dtype='str')]

# Departments

In [20]:
print(repr(df[["branch_name"]].drop_duplicates()))
print(df[["branch_name"]].drop_duplicates().count())

                                            branch_name
0                         BIO MEDICAL ENGINEERING  (SS)
1                                    CIVIL  ENGINEERING
2                 COMPUTER SCIENCE AND ENGINEERING (SS)
3                      COMPUTER SCIENCE AND ENGINEERING
4             ELECTRONICS AND COMMUNICATION ENGINEERING
...                                                 ...
2467                             Mechanical Engineering
835                  ENVIRONMENTAL SCIENCE & TECHNOLOGY
839                ROBOTICS AND ARTIFICIAL INTELLIGENCE
1138  COMPUTER SCIENCE AND ENGINEERING(ARTIFICIAL IN...
1408                                    Interior Design

[128 rows x 1 columns]
branch_name    128
dtype: int64

# Branches

In [21]:
branches: pd.DataFrame = df["branch_name"].to_frame()
branches

                                    branch_name
0                 BIO MEDICAL ENGINEERING  (SS)
1                            CIVIL  ENGINEERING
2         COMPUTER SCIENCE AND ENGINEERING (SS)
3              COMPUTER SCIENCE AND ENGINEERING
4     ELECTRONICS AND COMMUNICATION ENGINEERING
...                                         ...
3452                         CIVIL  ENGINEERING
3453           COMPUTER SCIENCE AND ENGINEERING
3454  ELECTRONICS AND COMMUNICATION ENGINEERING
3455     ELECTRICAL AND ELECTRONICS ENGINEERING
3456                     MECHANICAL ENGINEERING

[16174 rows x 1 columns]

In [22]:
branches.axes

[Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
        ...
        3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456],
       dtype='int64', length=16174),
 Index(['branch_name'], dtype='str')]

In [23]:
branches.drop_duplicates(inplace=True)

In [24]:
from collections import OrderedDict
import re

In [25]:
department_patterns: OrderedDict[str, list[str]] = OrderedDict({
    "Computer": [
        r"computer",
        r"information technology",
        r"information science",
        r"computer technology",
        r"cyber security",
    ],

    "Mechanical": [
        r"mechanical",
        r"mechatronics",
        r"automobile",
    ],

    "ECE": [
        r"electronics and communication",
        r"electronics and computer",
        r"electronics and telecommunication",
    ],

    "EEE": [
        r"electrical",
        r"electronic instrumentation",
    ],

    "Civil": [
        r"civil",
    ],

    "AI & Data Science": [
        r"artificial intelligence",
        r"data science",
    ],

    "Biotechnology": [
        r"bio technology",
        r"biotechnology",
        r"bio chemical",
        r"biomedical",
    ],

    "Agricultural": [
        r"agri",
    ],

    "Industrial": [
        r"industrial",
    ],

    "Food": [
        r"food technology",
    ],

    "Chemical": [
        r"chemical",
    ],

    "Petroleum": [
        r"petroleum",
        r"petro chemical",
    ],

    "Textile & Fashion": [
        r"textile",
        r"fashion",
        r"apparel",
        r"handloom",
    ],

    "Robotics": [
        r"robotics",
    ],

    "Production & Manufacturing": [
        r"production",
        r"manufacturing",
    ],

    "Pharmaceutical": [
        r"pharmaceutical",
        r"pharma",
    ],

    "Ceramic": [
        r"ceramic",
    ],

    "Instrumentation": [
        r"instrumentation",
        r"control engineering",
    ],

    "Aeronautical & Aerospace": [
        r"aeronautical",
        r"aerospace",
    ],

    "Printing": [
        r"printing",
    ],

    "Marine": [
        r"marine",
    ],

    "Metallurgical": [
        r"metallurgical",
    ],

    "Leather": [
        r"leather",
    ],

    "Plastic": [
        r"plastic",
        r"rubber",
    ],

    "Environmental": [
        r"environmental",
    ],

    "Petrochemical": [
        r"petro chemical",
    ],

    "Safety": [
        r"safety and fire",
    ],

    "Design": [
        r"interior design",
        r"bachelor of design",
    ],
    "Biomedical": [
        r"bio\s*medical"
    ],

    "Geoinformatics": [
        r"geo informatics",
    ],

    "Materials & Metallurgy": [
        r"material science",
        r"metallurgical",
    ],

    "Mining": [
        r"mining",
    ],

    "Architecture & Planning": [
        r"b\.plan",
        r"bplan",
    ],
    "Medical Electronics": [
        r"medical\s+electronics"

    ],
    "VLSI": [
        r"electronics\s+engineering.*vlsi"

    ],
    "Electronics and Telecommunication" : [
        r"electronics\s+and\s+telecommunication"
    ]
}
)

In [26]:
departments = pd.DataFrame({"canonical_name":department_patterns.keys()})

In [27]:
departments.values.tolist().index(["Computer"])

0

In [28]:
def push_department_data():
    departments.to_sql("department",engine,if_exists="append",index=False)

In [ ]:
# push_department_data()

In [30]:
def normalize_branch_name(name) -> str:
    name: str = str(name).strip().lower()
    name = re.sub(r"\s+", " ", name)
    return name




def classify_departments(branch_name) -> list:
    name: str = normalize_branch_name(branch_name)

    matched_departments: list[dict[int, str]] = []

    for department, patterns in department_patterns.items():
        for pattern in patterns:
            if re.search(pattern, name):
                matched_departments.append({get_dept_index(department):department})
                break 
    return matched_departments if matched_departments else [{-1:"Unlisted"}]

def get_dept_index(dept_name : str):
    return departments.values.tolist().index([dept_name])+1



branches["department"] = (
    branches["branch_name"]
    .apply(classify_departments)
)

In [31]:
unclassified = branches[
    branches["department"] == "Unlisted"
]["branch_name"].unique()

print("Unclassified:", len(unclassified))
print(unclassified)

Unclassified: 0
<StringArray>
[]
Length: 0, dtype: str

Logic:

Now to push the data into the branch table we need to get the department which it belongs to , so to fetch the department we can use our helper and get the department which the current branch belongs to and thenm we can get the index of it and add 1 solved

In [33]:
# departments.index+=1
departments

                       canonical_name
0                            Computer
1                          Mechanical
2                                 ECE
3                                 EEE
4                               Civil
..                                ...
31                             Mining
32            Architecture & Planning
33                Medical Electronics
34                               VLSI
35  Electronics and Telecommunication

[36 rows x 1 columns]

In [34]:
dept_list = departments.values.tolist()
dept_list

[['Computer'],
 ['Mechanical'],
 ['ECE'],
 ['EEE'],
 ['Civil'],
 ['AI & Data Science'],
 ['Biotechnology'],
 ['Agricultural'],
 ['Industrial'],
 ['Food'],
 ['Chemical'],
 ['Petroleum'],
 ['Textile & Fashion'],
 ['Robotics'],
 ['Production & Manufacturing'],
 ['Pharmaceutical'],
 ['Ceramic'],
 ['Instrumentation'],
 ['Aeronautical & Aerospace'],
 ['Printing'],
 ['Marine'],
 ['Metallurgical'],
 ['Leather'],
 ['Plastic'],
 ['Environmental'],
 ['Petrochemical'],
 ['Safety'],
 ['Design'],
 ['Biomedical'],
 ['Geoinformatics'],
 ['Materials & Metallurgy'],
 ['Mining'],
 ['Architecture & Planning'],
 ['Medical Electronics'],
 ['VLSI'],
 ['Electronics and Telecommunication']]

In [35]:
branches

,branch_name,department
0,BIO MEDICAL ENGINEERING (SS),[{29: 'Biomedical'}]
1,CIVIL ENGINEERING,[{5: 'Civil'}]
2,COMPUTER SCIENCE AND ENGINEERING (SS),[{1: 'Computer'}]
3,COMPUTER SCIENCE AND ENGINEERING,[{1: 'Computer'}]
4,ELECTRONICS AND COMMUNICATION ENGINEERING,[{3: 'ECE'}]
...,...,...
2467,Mechanical Engineering,[{2: 'Mechanical'}]
835,ENVIRONMENTAL SCIENCE & TECHNOLOGY,[{25: 'Environmental'}]
839,ROBOTICS AND ARTIFICIAL INTELLIGENCE,"[{6: 'AI & Data Science'}, {14: 'Robotics'}]"
1138,COMPUTER SCIENCE AND ENGINEERING(ARTIFICIAL IN...,"[{1: 'Computer'}, {6: 'AI & Data Science'}]"
1408,Interior Design,[{28: 'Design'}]

In [36]:
branches_data = df[["branch_code","branch_name","college_code","year"]]

In [37]:
branch_data_wo_year = df[["branch_code","branch_name","college_code","year"]]
branch_data_wo_year.drop_duplicates(inplace=True,subset=["branch_code","branch_name","college_code"],keep="first")

In [38]:
print("Before:", len(df))

print(
    df.duplicated(
        subset=["branch_code", "branch_name", "college_code"],
        keep=False
    ).sum()
)

Before: 16174
15693

In [38]:
college_data.reset_index(inplace=True)

In [39]:
branches_data.axes

[Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
        ...
        3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456],
       dtype='int64', length=16174),
 Index(['branch_code', 'branch_name', 'college_code', 'year'], dtype='str')]

In [40]:
branch_data_wo_year.axes

[Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
        ...
        3258, 3276, 3286, 3291, 3292, 3382, 3388, 3390, 3395, 3429],
       dtype='int64', length=4319),
 Index(['branch_code', 'branch_name', 'college_code', 'year'], dtype='str')]

In [41]:
branch_data_wo_year.axes

[Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
        ...
        3258, 3276, 3286, 3291, 3292, 3382, 3388, 3390, 3395, 3429],
       dtype='int64', length=4319),
 Index(['branch_code', 'branch_name', 'college_code', 'year'], dtype='str')]

In [44]:
def find_college_id(counselling_code):
    return int(college_data.index[college_data["counselling_code"] == counselling_code][0])

In [42]:
pd.DataFrame.index

In [47]:
find_college_id(1)

1

In [48]:
def prepare_branch_data(df : pd.DataFrame):
    df.rename(columns={"branch_code":"code","branch_name":"name"},inplace=True)
    df["college_id"] = df["college_code"].apply(find_college_id)
    df.reset_index(drop=True, inplace=True)
    df.drop(columns=["college_code"],inplace=True)
    return df

In [49]:
prepared_branch_data = prepare_branch_data(branches_data)

In [50]:
prepared_branch_data

      code                                       name  year  college_id
0       BY              BIO MEDICAL ENGINEERING  (SS)  2021           1
1       CE                         CIVIL  ENGINEERING  2021           1
2       CM      COMPUTER SCIENCE AND ENGINEERING (SS)  2021           1
3       CS           COMPUTER SCIENCE AND ENGINEERING  2021           1
4       EC  ELECTRONICS AND COMMUNICATION ENGINEERING  2021           1
...    ...                                        ...   ...         ...
16169   CE                         CIVIL  ENGINEERING  2025         467
16170   CS           COMPUTER SCIENCE AND ENGINEERING  2025         467
16171   EC  ELECTRONICS AND COMMUNICATION ENGINEERING  2025         467
16172   EE     ELECTRICAL AND ELECTRONICS ENGINEERING  2025         467
16173   ME                     MECHANICAL ENGINEERING  2025         467

[16174 rows x 4 columns]

In [51]:
def push_branch_data():
    prepared_branch_data.to_sql("branch",engine,if_exists="append",index=False)

In [ ]:
# push_branch_data()

# Allotments

In [85]:

years = [2021,2022,2023,2024,2025]


allot_df = pd.DataFrame()

allot_df_list: list[pd.DataFrame] = []

for year in years:
    df = pd.read_json(f"data/data{year}/allotments{year}.json")
    df = pd.json_normalize(list(df.get("data")))
    df["year"] = year

    allot_df_list.append(df)


allot_df = pd.concat(allot_df_list)
allot_df.reset_index()

,index,college_code,college_name,district,college_type,branch_code,branch_name,oc_initial,oc_filled,bc_initial,bc_filled,bcm_initial,bcm_filled,mbc_initial,mbc_filled,sc_initial,sc_filled,sca_initial,sca_filled,st_initial,st_filled,year
0,0,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,BY,BIO MEDICAL ENGINEERING (SS),16,16,14,14,2,2,1,1,8,8,2,2,1,1,2021
1,1,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CE,CIVIL ENGINEERING,16,16,14,14,2,2,1,1,8,8,2,2,1,1,2021
2,2,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CM,COMPUTER SCIENCE AND ENGINEERING (SS),31,31,25,25,4,4,3,3,17,17,3,3,1,1,2021
3,3,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CS,COMPUTER SCIENCE AND ENGINEERING,16,16,16,16,2,2,1,1,7,7,2,2,1,1,2021
4,4,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,16,16,14,14,1,1,2,2,8,8,1,1,1,1,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16169,3452,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CE,CIVIL ENGINEERING,8,4,6,0,1,0,5,0,2,0,0,0,1,0,2025
16170,3453,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CS,COMPUTER SCIENCE AND ENGINEERING,22,22,19,10,2,2,15,3,11,9,3,3,1,0,2025
16171,3454,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,11,11,10,1,1,0,7,0,6,1,1,0,0,0,2025
16172,3455,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EE,ELECTRICAL AND ELECTRONICS ENGINEERING,8,4,6,0,1,0,5,0,3,0,0,0,0,0,2025
16173,3456,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,ME,MECHANICAL ENGINEERING,15,5,13,0,2,0,8,0,8,0,1,0,1,0,2025

In [86]:
allot_df = allot_df[["branch_name","branch_code","college_code","oc_initial","oc_filled","bc_initial","bc_filled","bcm_initial","bcm_filled","mbc_initial","mbc_filled","sc_initial","sc_filled","sca_initial","sca_filled","st_initial","st_filled","year"]]

In [87]:
allot_df.reset_index(drop=True)
allot_df.index+=1

In [88]:
allot_df

,branch_name,branch_code,college_code,oc_initial,oc_filled,bc_initial,bc_filled,bcm_initial,bcm_filled,mbc_initial,mbc_filled,sc_initial,sc_filled,sca_initial,sca_filled,st_initial,st_filled,year
1,BIO MEDICAL ENGINEERING (SS),BY,1,16,16,14,14,2,2,1,1,8,8,2,2,1,1,2021
2,CIVIL ENGINEERING,CE,1,16,16,14,14,2,2,1,1,8,8,2,2,1,1,2021
3,COMPUTER SCIENCE AND ENGINEERING (SS),CM,1,31,31,25,25,4,4,3,3,17,17,3,3,1,1,2021
4,COMPUTER SCIENCE AND ENGINEERING,CS,1,16,16,16,16,2,2,1,1,7,7,2,2,1,1,2021
5,ELECTRONICS AND COMMUNICATION ENGINEERING,EC,1,16,16,14,14,1,1,2,2,8,8,1,1,1,1,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3453,CIVIL ENGINEERING,CE,5990,8,4,6,0,1,0,5,0,2,0,0,0,1,0,2025
3454,COMPUTER SCIENCE AND ENGINEERING,CS,5990,22,22,19,10,2,2,15,3,11,9,3,3,1,0,2025
3455,ELECTRONICS AND COMMUNICATION ENGINEERING,EC,5990,11,11,10,1,1,0,7,0,6,1,1,0,0,0,2025
3456,ELECTRICAL AND ELECTRONICS ENGINEERING,EE,5990,8,4,6,0,1,0,5,0,3,0,0,0,0,0,2025
3457,MECHANICAL ENGINEERING,ME,5990,15,5,13,0,2,0,8,0,8,0,1,0,1,0,2025

In [89]:
def get_college_index(row, college_data):
    return college_data.index[college_data["counselling_code"] == row["college_code"]][0]

In [90]:
def get_branch_index(row, branch_df):
    mask = (
        (branch_df["name"] == row["branch_name"]) &
        (branch_df["year"] == row["year"]) &
        (branch_df["college_id"] == row["college_id"])
    )
    return branch_df.index[mask][0]+1

In [91]:
def prepare_allotment_data(df, college_df):
    df["college_id"] = df.apply(get_college_index,axis=1,college_data=college_data)
    df["branch_id"] = df.apply(get_branch_index,axis=1,branch_df = prepared_branch_data)
    return df

In [92]:
prepare_allotment_data(allot_df,college_data)

,branch_name,branch_code,college_code,oc_initial,oc_filled,bc_initial,bc_filled,bcm_initial,bcm_filled,mbc_initial,mbc_filled,sc_initial,sc_filled,sca_initial,sca_filled,st_initial,st_filled,year,college_id,branch_id
1,BIO MEDICAL ENGINEERING (SS),BY,1,16,16,14,14,2,2,1,1,8,8,2,2,1,1,2021,1,1
2,CIVIL ENGINEERING,CE,1,16,16,14,14,2,2,1,1,8,8,2,2,1,1,2021,1,2
3,COMPUTER SCIENCE AND ENGINEERING (SS),CM,1,31,31,25,25,4,4,3,3,17,17,3,3,1,1,2021,1,3
4,COMPUTER SCIENCE AND ENGINEERING,CS,1,16,16,16,16,2,2,1,1,7,7,2,2,1,1,2021,1,4
5,ELECTRONICS AND COMMUNICATION ENGINEERING,EC,1,16,16,14,14,1,1,2,2,8,8,1,1,1,1,2021,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3453,CIVIL ENGINEERING,CE,5990,8,4,6,0,1,0,5,0,2,0,0,0,1,0,2025,467,16170
3454,COMPUTER SCIENCE AND ENGINEERING,CS,5990,22,22,19,10,2,2,15,3,11,9,3,3,1,0,2025,467,16171
3455,ELECTRONICS AND COMMUNICATION ENGINEERING,EC,5990,11,11,10,1,1,0,7,0,6,1,1,0,0,0,2025,467,16172
3456,ELECTRICAL AND ELECTRONICS ENGINEERING,EE,5990,8,4,6,0,1,0,5,0,3,0,0,0,0,0,2025,467,16173
3457,MECHANICAL ENGINEERING,ME,5990,15,5,13,0,2,0,8,0,8,0,1,0,1,0,2025,467,16174

In [93]:
allot_df = allot_df[["bc_filled" ,"bc_initial" , "bcm_filled" ,"bcm_initial", "mbc_filled" , "mbc_initial" , "oc_filled","oc_initial","sc_filled","sc_initial","sca_filled","sca_initial","st_filled","st_initial","branch_id","college_id","year" ]]
allot_df

,bc_filled,bc_initial,bcm_filled,bcm_initial,mbc_filled,mbc_initial,oc_filled,oc_initial,sc_filled,sc_initial,sca_filled,sca_initial,st_filled,st_initial,branch_id,college_id,year
1,14,14,2,2,1,1,16,16,8,8,2,2,1,1,1,1,2021
2,14,14,2,2,1,1,16,16,8,8,2,2,1,1,2,1,2021
3,25,25,4,4,3,3,31,31,17,17,3,3,1,1,3,1,2021
4,16,16,2,2,1,1,16,16,7,7,2,2,1,1,4,1,2021
5,14,14,1,1,2,2,16,16,8,8,1,1,1,1,5,1,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3453,0,6,0,1,0,5,4,8,0,2,0,0,0,1,16170,467,2025
3454,10,19,2,2,3,15,22,22,9,11,3,3,0,1,16171,467,2025
3455,1,10,0,1,0,7,11,11,1,6,0,1,0,0,16172,467,2025
3456,0,6,0,1,0,5,4,8,0,3,0,0,0,0,16173,467,2025
3457,0,13,0,2,0,8,5,15,0,8,0,1,0,1,16174,467,2025

In [ ]:
def push_allotment_data():
    allot_df.to_sql("allotment",engine,if_exists="append",index=False)

In [ ]:
# push_allotment_data()

# Rank

In [116]:

years = [2021,2022,2023,2024,2025]


rank_df = pd.DataFrame()

rank_df_list: list[pd.DataFrame] = []

for year in years:
    df = pd.read_json(f"data/data{year}/rank{year}.json")
    df = pd.json_normalize(list(df.get("data")))
    df["year"] = year

    int_cols = ["bc", "bcm", "mbc", "oc", "sc", "sca", "st"]

    partial_cols = ["bc_partial", "bcm_partial", "mbc_partial", "oc_partial", "sc_partial", "sca_partial", "st_partial"]

    df[int_cols] = df[int_cols].astype("Int64")
    df[partial_cols] = df[partial_cols].fillna(False).astype(bool)

    rank_df_list.append(df)


rank_df = pd.concat(rank_df_list)
rank_df.reset_index()

,index,college_code,college_name,district,college_type,branch_code,branch_name,oc,bc,bcm,mbc,sc,sca,st,oc_partial,bc_partial,bcm_partial,mbc_partial,sc_partial,sca_partial,st_partial,year
0,0,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,BY,BIO MEDICAL ENGINEERING (SS),1248,1998,2390,1420,8937,22463,26147,False,False,False,False,False,False,False,2021
1,1,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CE,CIVIL ENGINEERING,2326,3227,6363,2527,7316,23541,43295,False,False,False,False,False,False,False,2021
2,2,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CM,COMPUTER SCIENCE AND ENGINEERING (SS),175,260,631,312,2940,3853,5838,False,False,False,False,False,False,False,2021
3,3,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CS,COMPUTER SCIENCE AND ENGINEERING,29,111,388,67,551,2101,3779,False,False,False,False,False,False,False,2021
4,4,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,218,332,789,368,1680,4067,3514,False,False,False,False,False,False,False,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16169,3452,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CE,CIVIL ENGINEERING,237651,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,False,False,False,False,2025
16170,3453,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CS,COMPUTER SCIENCE AND ENGINEERING,190752,232127,238106,211816,237394,234965,<NA>,False,True,False,True,True,False,False,2025
16171,3454,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,236516,239156,<NA>,<NA>,239200,<NA>,<NA>,False,True,False,False,True,False,False,2025
16172,3455,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EE,ELECTRICAL AND ELECTRONICS ENGINEERING,211925,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,False,False,False,False,2025
16173,3456,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,ME,MECHANICAL ENGINEERING,234456,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,False,False,False,False,2025

In [117]:
def get_college_index(row, college_data):
    return college_data.index[college_data["counselling_code"] == row["college_code"]][0]

In [118]:
def get_branch_index(row, branch_df):
    mask = (
        (branch_df["name"] == row["branch_name"]) &
        (branch_df["year"] == row["year"]) &
        (branch_df["college_id"] == row["college_id"])
    )
    return branch_df.index[mask][0]+1

In [119]:
def prepare_rank_data(df, college_df, branch_df):
    df["college_id"] = df.apply(get_college_index,axis=1,college_data=college_df)
    df["branch_id"] = df.apply(get_branch_index,axis=1,branch_df = branch_df)
    return df

In [120]:
prepare_rank_data(rank_df,college_data,prepared_branch_data)

,college_code,college_name,district,college_type,branch_code,branch_name,oc,bc,bcm,mbc,sc,sca,st,oc_partial,bc_partial,bcm_partial,mbc_partial,sc_partial,sca_partial,st_partial,year,college_id,branch_id
0,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,BY,BIO MEDICAL ENGINEERING (SS),1248,1998,2390,1420,8937,22463,26147,False,False,False,False,False,False,False,2021,1,1
1,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CE,CIVIL ENGINEERING,2326,3227,6363,2527,7316,23541,43295,False,False,False,False,False,False,False,2021,1,2
2,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CM,COMPUTER SCIENCE AND ENGINEERING (SS),175,260,631,312,2940,3853,5838,False,False,False,False,False,False,False,2021,1,3
3,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CS,COMPUTER SCIENCE AND ENGINEERING,29,111,388,67,551,2101,3779,False,False,False,False,False,False,False,2021,1,4
4,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,218,332,789,368,1680,4067,3514,False,False,False,False,False,False,False,2021,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CE,CIVIL ENGINEERING,237651,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,False,False,False,False,2025,467,16170
3453,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CS,COMPUTER SCIENCE AND ENGINEERING,190752,232127,238106,211816,237394,234965,<NA>,False,True,False,True,True,False,False,2025,467,16171
3454,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,236516,239156,<NA>,<NA>,239200,<NA>,<NA>,False,True,False,False,True,False,False,2025,467,16172
3455,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EE,ELECTRICAL AND ELECTRONICS ENGINEERING,211925,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,False,False,False,False,2025,467,16173
3456,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,ME,MECHANICAL ENGINEERING,234456,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,False,False,False,False,False,False,2025,467,16174

In [121]:

rank_df = rank_df[[ "bc", "bc_partial", "bcm", "bcm_partial", "mbc", "mbc_partial", "oc", "oc_partial", "sc", "sc_partial", "sca", "sca_partial", "st", "st_partial", "year", "branch_id", "college_id"]]

In [122]:
rank_df

,bc,bc_partial,bcm,bcm_partial,mbc,mbc_partial,oc,oc_partial,sc,sc_partial,sca,sca_partial,st,st_partial,year,branch_id,college_id
0,1998,False,2390,False,1420,False,1248,False,8937,False,22463,False,26147,False,2021,1,1
1,3227,False,6363,False,2527,False,2326,False,7316,False,23541,False,43295,False,2021,2,1
2,260,False,631,False,312,False,175,False,2940,False,3853,False,5838,False,2021,3,1
3,111,False,388,False,67,False,29,False,551,False,2101,False,3779,False,2021,4,1
4,332,False,789,False,368,False,218,False,1680,False,4067,False,3514,False,2021,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452,<NA>,False,<NA>,False,<NA>,False,237651,True,<NA>,False,<NA>,False,<NA>,False,2025,16170,467
3453,232127,True,238106,False,211816,True,190752,False,237394,True,234965,False,<NA>,False,2025,16171,467
3454,239156,True,<NA>,False,<NA>,False,236516,False,239200,True,<NA>,False,<NA>,False,2025,16172,467
3455,<NA>,False,<NA>,False,<NA>,False,211925,True,<NA>,False,<NA>,False,<NA>,False,2025,16173,467
3456,<NA>,False,<NA>,False,<NA>,False,234456,True,<NA>,False,<NA>,False,<NA>,False,2025,16174,467

In [123]:
def push_rank_df():
    rank_df.to_sql("rank",engine,if_exists="append",index=False)

In [ ]:
# push_rank_df()

# Cutoff

In [129]:

years = [2021,2022,2023,2024,2025]


cutoff_df = pd.DataFrame()

cutoff_df_list: list[pd.DataFrame] = []

for year in years:
    df = pd.read_json(f"data/data{year}/rank{year}.json")
    df = pd.json_normalize(list(df.get("data")))
    df["year"] = year

    float_cols = ["bc", "bcm", "mbc", "oc", "sc", "sca", "st"]

    partial_cols = ["bc_partial", "bcm_partial", "mbc_partial", "oc_partial", "sc_partial", "sca_partial", "st_partial"]

    df[float_cols] = df[int_cols].astype("float")
    df[partial_cols] = df[partial_cols].fillna(False).astype(bool)

    cutoff_df_list.append(df)


cutoff_df = pd.concat(cutoff_df_list)
cutoff_df.reset_index()

,index,college_code,college_name,district,college_type,branch_code,branch_name,oc,bc,bcm,mbc,sc,sca,st,oc_partial,bc_partial,bcm_partial,mbc_partial,sc_partial,sca_partial,st_partial,year
0,0,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,BY,BIO MEDICAL ENGINEERING (SS),1248.0,1998.0,2390.0,1420.0,8937.0,22463.0,26147.0,False,False,False,False,False,False,False,2021
1,1,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CE,CIVIL ENGINEERING,2326.0,3227.0,6363.0,2527.0,7316.0,23541.0,43295.0,False,False,False,False,False,False,False,2021
2,2,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CM,COMPUTER SCIENCE AND ENGINEERING (SS),175.0,260.0,631.0,312.0,2940.0,3853.0,5838.0,False,False,False,False,False,False,False,2021
3,3,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CS,COMPUTER SCIENCE AND ENGINEERING,29.0,111.0,388.0,67.0,551.0,2101.0,3779.0,False,False,False,False,False,False,False,2021
4,4,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,218.0,332.0,789.0,368.0,1680.0,4067.0,3514.0,False,False,False,False,False,False,False,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16169,3452,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CE,CIVIL ENGINEERING,237651.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,2025
16170,3453,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CS,COMPUTER SCIENCE AND ENGINEERING,190752.0,232127.0,238106.0,211816.0,237394.0,234965.0,NaN,False,True,False,True,True,False,False,2025
16171,3454,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,236516.0,239156.0,NaN,NaN,239200.0,NaN,NaN,False,True,False,False,True,False,False,2025
16172,3455,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EE,ELECTRICAL AND ELECTRONICS ENGINEERING,211925.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,2025
16173,3456,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,ME,MECHANICAL ENGINEERING,234456.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,2025

In [130]:
def get_college_index(row, college_data):
    return college_data.index[college_data["counselling_code"] == row["college_code"]][0]

In [131]:
def get_branch_index(row, branch_df):
    mask = (
        (branch_df["name"] == row["branch_name"]) &
        (branch_df["year"] == row["year"]) &
        (branch_df["college_id"] == row["college_id"])
    )
    return branch_df.index[mask][0]+1

In [132]:
def prepare_cutoff_data(df, college_df, branch_df):
    df["college_id"] = df.apply(get_college_index,axis=1,college_data=college_df)
    df["branch_id"] = df.apply(get_branch_index,axis=1,branch_df = branch_df)
    return df

In [134]:
prepare_cutoff_data(cutoff_df,college_data,prepared_branch_data)

,college_code,college_name,district,college_type,branch_code,branch_name,oc,bc,bcm,mbc,sc,sca,st,oc_partial,bc_partial,bcm_partial,mbc_partial,sc_partial,sca_partial,st_partial,year,college_id,branch_id
0,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,BY,BIO MEDICAL ENGINEERING (SS),1248.0,1998.0,2390.0,1420.0,8937.0,22463.0,26147.0,False,False,False,False,False,False,False,2021,1,1
1,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CE,CIVIL ENGINEERING,2326.0,3227.0,6363.0,2527.0,7316.0,23541.0,43295.0,False,False,False,False,False,False,False,2021,1,2
2,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CM,COMPUTER SCIENCE AND ENGINEERING (SS),175.0,260.0,631.0,312.0,2940.0,3853.0,5838.0,False,False,False,False,False,False,False,2021,1,3
3,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CS,COMPUTER SCIENCE AND ENGINEERING,29.0,111.0,388.0,67.0,551.0,2101.0,3779.0,False,False,False,False,False,False,False,2021,1,4
4,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,218.0,332.0,789.0,368.0,1680.0,4067.0,3514.0,False,False,False,False,False,False,False,2021,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CE,CIVIL ENGINEERING,237651.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,2025,467,16170
3453,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,CS,COMPUTER SCIENCE AND ENGINEERING,190752.0,232127.0,238106.0,211816.0,237394.0,234965.0,NaN,False,True,False,True,True,False,False,2025,467,16171
3454,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,236516.0,239156.0,NaN,NaN,239200.0,NaN,NaN,False,True,False,False,True,False,False,2025,467,16172
3455,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,EE,ELECTRICAL AND ELECTRONICS ENGINEERING,211925.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,2025,467,16173
3456,5990,"Latha Mathavan Engineering College, Latha Math...",MADURAI,SELF FINANCING COLLEGES TIER 3,ME,MECHANICAL ENGINEERING,234456.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,2025,467,16174

In [135]:

cutoff_df = cutoff_df[[ "bc", "bc_partial", "bcm", "bcm_partial", "mbc", "mbc_partial", "oc", "oc_partial", "sc", "sc_partial", "sca", "sca_partial", "st", "st_partial", "year", "branch_id", "college_id"]]

In [136]:
cutoff_df

,bc,bc_partial,bcm,bcm_partial,mbc,mbc_partial,oc,oc_partial,sc,sc_partial,sca,sca_partial,st,st_partial,year,branch_id,college_id
0,1998.0,False,2390.0,False,1420.0,False,1248.0,False,8937.0,False,22463.0,False,26147.0,False,2021,1,1
1,3227.0,False,6363.0,False,2527.0,False,2326.0,False,7316.0,False,23541.0,False,43295.0,False,2021,2,1
2,260.0,False,631.0,False,312.0,False,175.0,False,2940.0,False,3853.0,False,5838.0,False,2021,3,1
3,111.0,False,388.0,False,67.0,False,29.0,False,551.0,False,2101.0,False,3779.0,False,2021,4,1
4,332.0,False,789.0,False,368.0,False,218.0,False,1680.0,False,4067.0,False,3514.0,False,2021,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452,NaN,False,NaN,False,NaN,False,237651.0,True,NaN,False,NaN,False,NaN,False,2025,16170,467
3453,232127.0,True,238106.0,False,211816.0,True,190752.0,False,237394.0,True,234965.0,False,NaN,False,2025,16171,467
3454,239156.0,True,NaN,False,NaN,False,236516.0,False,239200.0,True,NaN,False,NaN,False,2025,16172,467
3455,NaN,False,NaN,False,NaN,False,211925.0,True,NaN,False,NaN,False,NaN,False,2025,16173,467
3456,NaN,False,NaN,False,NaN,False,234456.0,True,NaN,False,NaN,False,NaN,False,2025,16174,467

In [137]:
def push_cutoff_df():
    rank_df.to_sql("cutoff",engine,if_exists="append",index=False)

In [138]:
push_cutoff_df()