In [1]:
# !pip install pandas
# !pip install SQLAlchemy
# !pip install psycopg2
# !pip install pyrefly

In [2]:
import pandas as pd
import sqlalchemy as sql

pd.set_option("display.max_rows", 130)
pd.set_option("display.max_columns", 50)

In [3]:
df: pd.DataFrame = pd.read_json("data/data2021/allotments2021.json")
df = pd.json_normalize(list(df.get("data")))
df

,college_code,college_name,district,college_type,branch_code,branch_name,oc_initial,oc_filled,bc_initial,bc_filled,bcm_initial,bcm_filled,mbc_initial,mbc_filled,sc_initial,sc_filled,sca_initial,sca_filled,st_initial,st_filled
0,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,BY,BIO MEDICAL ENGINEERING (SS),16,16,14,14,2,2,1,1,8,8,2,2,1,1
1,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CE,CIVIL ENGINEERING,16,16,14,14,2,2,1,1,8,8,2,2,1,1
2,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CM,COMPUTER SCIENCE AND ENGINEERING (SS),31,31,25,25,4,4,3,3,17,17,3,3,1,1
3,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,CS,COMPUTER SCIENCE AND ENGINEERING,16,16,16,16,2,2,1,1,7,7,2,2,1,1
4,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,16,16,14,14,1,1,2,2,8,8,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2825,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,CE,CIVIL ENGINEERING,16,3,14,0,2,0,1,0,9,0,2,0,0,0
2826,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,CS,COMPUTER SCIENCE AND ENGINEERING,16,16,13,13,2,2,1,0,7,2,1,0,1,0
2827,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,EC,ELECTRONICS AND COMMUNICATION ENGINEERING,16,10,14,0,2,0,1,0,7,0,2,0,1,0
2828,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,EE,ELECTRICAL AND ELECTRONICS ENGINEERING,8,5,6,0,1,0,1,0,4,0,1,0,0,0
2829,5990,"Latha Mathavan Engineering College, Kidaripatt...",MADURAI,SELF FINANCING COLLEGES TIER 3,ME,MECHANICAL ENGINEERING,25,12,22,0,3,0,2,0,12,0,1,0,1,0

In [4]:
years = [2021,2022,2023,2024,2025]


df = pd.DataFrame()

df_list: list[pd.DataFrame] = []

for year in years:
    df = pd.read_json(f"data/data{year}/allotments{year}.json")
    df = pd.json_normalize(list(df.get("data")))
    df_list.append(df)


df = pd.concat(df_list)

df.drop_duplicates(inplace=True)

In [5]:
# First taking the college data from it 

college_data : pd.DataFrame = df[["college_code","college_name","district","college_type"]]

In [6]:
college_data.drop_duplicates()

,college_code,college_name,district,college_type
0,1,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS
17,2,"University Departments of Anna University, Che...",CHENNAI,CEG DEPTS
28,4,"University Departments of Anna University, Che...",CHENGALPET,CEG DEPTS
39,1516,Thanthai Periyar Government Institute of Techn...,VELLORE,GOVERNMENT ENGG COLLEGES
44,2005,"Government College of Technology (Autonomous),...",COIMBATORE,GOVERNMENT ENGG COLLEGES
...,...,...,...,...
3250,5545,"G.T.N COLLEGE OF TECHNOLOGY, OLD KARUR ROAD, D...",DINDIGUL,SELF FINANCING COLLEGES TIER 3
3255,5546,"Jamal Mohamed College of Engineering, NH-45, T...",DINDIGUL,SELF FINANCING COLLEGES TIER 3
3293,5862,"RVS School of Engineering and Technology, (For...",DINDIGUL,SELF FINANCING COLLEGES TIER 3
3325,5907,Mohamed Sathak Engineering College (Autonomous...,RAMANATHAPURAM,SELF FINANCING COLLEGES TIER 3
3381,5914,Solamalai College of Engineering (Autonomous)...,MADURAI,SELF FINANCING COLLEGES TIER 3

In [7]:
#Data cleaning 

def remove_repeated_colleges(df : pd.DataFrame):
    df = df.drop_duplicates(subset=["college_code"], keep="last")

In [8]:
def find_financial_status(val : str) -> str:
    if(val == "CEG DEPTS"):
        return "GOVT"
    elif(val == "GOVERNMENT ENGG COLLEGES"):
        return "GOVT"
    elif(val == "GOVERNMENT AIDED COLLEGES"):
        return "AIDED"
    elif(val == "CENTRAL GOVERNMENT ENGG COLLEGES COLLEGES"):
        return "GOVT"
    elif(val == "UNIV CONSTITUENT COLLEGES"):
        return "GOVT"
    elif(val == "ANNAMALAI UNIV"):
        return "GOVT"
    elif(val == "SELF FINANCING COLLEGES TIER 3"):
        return "PRIVATE"
    elif(val == "SELF FINANCING COLLEGES TIER 2"):
        return "PRIVATE"
    elif(val == "SELF FINANCING COLLEGES TIER 1"):
        return "PRIVATE"


def find_college_tier(val : str) -> str:
    if(val == "CEG DEPTS"):
        return "CEG"
    elif(val == "GOVERNMENT ENGG COLLEGES"):
        return "GOVT"
    elif(val == "GOVERNMENT AIDED COLLEGES"):
        return "AIDED"
    elif(val == "CENTRAL GOVERNMENT ENGG COLLEGES COLLEGES"):
        return "CENT_GOVT"
    elif(val == "UNIV CONSTITUENT COLLEGES"):
        return "ANNA_UNIV"
    elif(val == "ANNAMALAI UNIV"):
        return "ANNAMALAI_UNIV"
    elif(val == "SELF FINANCING COLLEGES TIER 3"):
        return "TIER 3"
    elif(val == "SELF FINANCING COLLEGES TIER 2"):
        return "TIER 2"
    elif(val == "SELF FINANCING COLLEGES TIER 1"):
        return "TIER 1"





# Snippet to extract the data needed for the college for the college table in the schema
def extract_college_data(year : int) -> str:
    df = pd.read_json(f"data/data{year}/allotments{year}.json")
    df = pd.json_normalize(list(df.get("data")))
    college_data = df[["college_type","college_code","district","college_name"]]
    college_data.drop_duplicates(inplace=True)
    college_data.rename(columns={"college_type":"category"},inplace=True)
    college_data.rename(columns={"college_code":"counselling_code"},inplace=True)
    college_data.rename(columns={"college_name":"name"},inplace=True)
    college_data["financial_status"] = college_data["category"].apply(find_financial_status)
    college_data["tier"] = college_data["category"].apply(find_college_tier)
    return college_data



college_data = pd.DataFrame()


data: list[pd.DataFrame] = []

for year in years:
    data.append(extract_college_data(year))


college_data = pd.concat(data)
college_data.drop_duplicates(inplace=True)
    

remove_repeated_colleges(college_data)

KeyError: Index(['college_code'], dtype='str')

In [ ]:
def push_college_data_to_table(college_data : pd.DataFrame) -> None:
    college_data.to_sql("college",con=engine,if_exists="append",index=False)

In [ ]:
engine: pd.Engine = sql.create_engine("postgresql+psycopg2://tneaadmin:tneadb@localhost:5432/tneadb")

conn = sql.Connection(engine)

In [ ]:
print(conn.exec_driver_sql("SELECT * FROM college").keys())

RMKeyView(['id', 'category', 'counselling_code', 'district', 'name', 'web_link', 'latitude', 'longitude', 'financial_status', 'tier'])

In [ ]:
# push_college_data_to_table(college_data)

In [9]:
college_data.axes

[Index([   0,   17,   28,   39,   44,   53,   58,   62,   68,   75,
        ...
        2787, 2962, 3142, 3149, 3212, 3250, 3255, 3293, 3325, 3381],
       dtype='int64', length=1359),
 Index(['category', 'counselling_code', 'district', 'name', 'financial_status',
        'tier'],
       dtype='str')]

To get the departments possible

In [10]:
print(repr(df[["branch_name"]].drop_duplicates()))
print(df[["branch_name"]].drop_duplicates().count())

                                            branch_name
0                         BIO MEDICAL ENGINEERING  (SS)
1                                    CIVIL  ENGINEERING
2                 COMPUTER SCIENCE AND ENGINEERING (SS)
3                      COMPUTER SCIENCE AND ENGINEERING
4             ELECTRONICS AND COMMUNICATION ENGINEERING
5                ELECTRICAL AND ELECTRONICS ENGINEERING
6        ELECTRONICS AND COMMUNICATION ENGINEERING (SS)
7                                       GEO INFORMATICS
8                                INDUSTRIAL ENGINEERING
9                           INFORMATION TECHNOLOGY (SS)
10                MATERIAL SCIENCE AND ENGINEERING (SS)
11                               MECHANICAL ENGINEERING
12                                   MINING ENGINEERING
13                            MANUFACTURING ENGINEERING
14                                  PRINTING TECHNOLOGY
15                     CIVIL ENGINEERING (TAMIL MEDIUM)
16                MECHANICAL ENGINEERING (TAMIL MEDIUM)
17                              APPAREL TECHNOLOGY (SS)
18                                CHEMICAL  ENGINEERING
19                           CHEMICAL  ENGINEERING (SS)
20                              CERAMIC TECHNOLOGY (SS)
21                                 FOOD TECHNOLOGY (SS)
22                            INDUSTRIAL BIO TECHNOLOGY
23                       INDUSTRIAL BIO TECHNOLOGY (SS)
24                                   LEATHER TECHNOLOGY
25                       PHARMACEUTICAL TECHNOLOGY (SS)
26            PETROLEUM ENGINEERING AND TECHNOLOGY (SS)
27                                   TEXTILE TECHNOLOGY
28                             AERONAUTICAL ENGINEERING
29                               AUTOMOBILE ENGINEERING
33          ELECTRONICS AND INSTRUMENTATION ENGINEERING
36                          MECHANICAL ENGINEERING (SS)
37                               PRODUCTION ENGINEERING
38                        RUBBER AND PLASTIC TECHNOLOGY
50                               INFORMATION TECHNOLOGY
67                            METALLURGICAL ENGINEERING
100                         AUTOMOBILE ENGINEERING (SS)
101                                 BIO TECHNOLOGY (SS)
105                             CIVIL  ENGINEERING (SS)
109          ELECTRICAL AND ELECTRONICS (SANDWICH) (SS)
110                             FASHION TECHNOLOGY (SS)
112        INSTRUMENTATION AND CONTROL ENGINEERING (SS)
115              MECHANICAL ENGINEERING (SANDWICH) (SS)
117                      METALLURGICAL ENGINEERING (SS)
118                         PRODUCTION ENGINEERING (SS)
120              PRODUCTION ENGINEERING (SANDWICH) (SS)
121                        ROBOTICS AND AUTOMATION (SS)
122                             TEXTILE TECHNOLOGY (SS)
124       ARTIFICIAL INTELLIGENCE AND DATA SCIENCE (SS)
134         ELECTRICAL AND ELECTRONICS ENGINEERING (SS)
142           Computer Science and Business System (SS)
150                                   MECHATRONICS (SS)
152                                  PLASTIC TECHNOLOGY
153                     HANDLOOM AND TEXTILE TECHNOLOGY
154     CHEMICAL AND ELECTRO CHEMICAL  ENGINEERING (SS)
179                                      BIO TECHNOLOGY
186                           PETRO CHEMICAL TECHNOLOGY
187                           PHARMACEUTICAL TECHNOLOGY
255   COMPUTER SCIENCE AND ENGINEERING (AI AND MACHI...
257     COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)
260                  CIVIL AND STRUCTUTURAL ENGINEERING
266              MECHANICAL ENGINEERING (MANUFACTURING)
284                                     FOOD TECHNOLOGY
286            Artificial Intelligence and Data Science
293                            Mechatronics Engineering
294        Artificial Intelligence and Machine Learning
295               COMPUTER SCIENCE AND BUSSINESS SYSTEM
301                         COMPUTER SCIENCE AND DESIGN
324                             BIO MEDICAL ENGINEERING
353                                  MARINE ENGINEERING
361                             AGRICULTURE ENGINEERING
365                             ROBOTICS AND AUTOMATION
431             COMPUTER AND  COMMUNICATION ENGINEERING
460                               PETROLEUM ENGINEERING
472                     MEDICAL ELECTRONICS ENGINEERING
483                   MECHANICAL ENGINEERING (SANDWICH)
484               MECHANICAL AND AUTOMATION ENGINEERING
636                               AEROSPACE ENGINEERING
642                                  FASHION TECHNOLOGY
811   M.Tech. Computer Science and Engineering (Inte...
816             INSTRUMENTATION AND CONTROL ENGINEERING
834                                      Cyber Security
1098           COMPUTER SCIENCE AND ENGINEERING (TAMIL)
1240                         PHARMACEUTICAL ENGINEERING
1264                                       MECHATRONICS
1280                        Safety and Fire Engineering
1289                                  TEXTILE CHEMISTRY
1312                    Computer Science and Technology
1533                                COMPUTER TECHNOLOGY
1542                Information Science and Engineering
1602     ELECTRONICS AND  TELECOMMUNICATION ENGINEERING
1605  Computer Science and Engineering (Cyber Security)
1759                         PETRO CHEMICAL ENGINEERING
1778  Mechanical and Mechatronics Engineering (Addit...
1779  Computer Science and Engineering (Internet of ...
1927                          ENVIRONMENTAL ENGINEERING
1930        Bio Technology and Bio Chemical Engineering
2434              INDUSTRIAL ENGINEERING AND MANAGEMENT
14                      PRINTING AND PACKING TECHNOLOGY
28                                               B.Plan
106   Computer Science and Engineering (Artificial I...
177            ARTIFICIAL INTELLIGENCE AND DATA SCIENCE
258   COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL I...
381                            AGRICULTURAL ENGINEERING
498   Computer Science and Engineering (Internet of ...
309   Electronics and Communication ( Advanced Commu...
312   Electronics Engineering (VLSI design and Techn...
6     Electronics Engineering (VLSI Design and Techn...
15                        PRINTING & PACKING TECHNOLOGY
152                                Interior Design (SS)
184   Electronics Engineering (VLSI Design and Techn...
190       Civil Engineering (Environmental Engineering)
194                 Electrical and Computer Engineering
197                 Mechanical Engineering (Automobile)
199                  Mechanical and Smart Manufacturing
334   Electronics and Communication (Advanced Commun...
412                                 MEDICAL ELECTRONICS
883                                  Bachelor of Design
993   Electronic Instrumentation and Control Enginee...
1590               Electronics and Computer Engineering
2464                                  Civil Engineering
2465                   Computer Science and Engineering
2466             Electrical and Electronics Engineering
2467                             Mechanical Engineering
835                  ENVIRONMENTAL SCIENCE & TECHNOLOGY
839                ROBOTICS AND ARTIFICIAL INTELLIGENCE
1138  COMPUTER SCIENCE AND ENGINEERING(ARTIFICIAL IN...
1408                                    Interior Design
branch_name    128
dtype: int64

In [11]:
branches: pd.DataFrame = df["branch_name"].to_frame()
branches

                                    branch_name
0                 BIO MEDICAL ENGINEERING  (SS)
1                            CIVIL  ENGINEERING
2         COMPUTER SCIENCE AND ENGINEERING (SS)
3              COMPUTER SCIENCE AND ENGINEERING
4     ELECTRONICS AND COMMUNICATION ENGINEERING
...                                         ...
3452                         CIVIL  ENGINEERING
3453           COMPUTER SCIENCE AND ENGINEERING
3454  ELECTRONICS AND COMMUNICATION ENGINEERING
3455     ELECTRICAL AND ELECTRONICS ENGINEERING
3456                     MECHANICAL ENGINEERING

[16157 rows x 1 columns]

In [12]:
branches.axes

[Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
        ...
        3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456],
       dtype='int64', length=16157),
 Index(['branch_name'], dtype='str')]

In [13]:
branches.drop_duplicates(inplace=True)

In [14]:
from collections import OrderedDict
import re

In [ ]:
department_patterns: OrderedDict[str, list[str]] = OrderedDict({
    "Computer": [
        r"computer",
        r"information technology",
        r"information science",
        r"computer technology",
        r"cyber security",
    ],

    "Mechanical": [
        r"mechanical",
        r"mechatronics",
        r"automobile",
    ],

    "ECE": [
        r"electronics and communication",
        r"electronics and computer",
        r"electronics and telecommunication",
    ],

    "EEE": [
        r"electrical",
        r"electronic instrumentation",
    ],

    "Civil": [
        r"civil",
    ],

    "AI & Data Science": [
        r"artificial intelligence",
        r"data science",
    ],

    "Biotechnology": [
        r"bio technology",
        r"biotechnology",
        r"bio chemical",
        r"biomedical",
    ],

    "Agricultural": [
        r"agri",
    ],

    "Industrial": [
        r"industrial",
    ],

    "Food": [
        r"food technology",
    ],

    "Chemical": [
        r"chemical",
    ],

    "Petroleum": [
        r"petroleum",
        r"petro chemical",
    ],

    "Textile & Fashion": [
        r"textile",
        r"fashion",
        r"apparel",
        r"handloom",
    ],

    "Robotics": [
        r"robotics",
    ],

    "Production & Manufacturing": [
        r"production",
        r"manufacturing",
    ],

    "Pharmaceutical": [
        r"pharmaceutical",
        r"pharma",
    ],

    "Ceramic": [
        r"ceramic",
    ],

    "Instrumentation": [
        r"instrumentation",
        r"control engineering",
    ],

    "Aeronautical & Aerospace": [
        r"aeronautical",
        r"aerospace",
    ],

    "Printing": [
        r"printing",
    ],

    "Marine": [
        r"marine",
    ],

    "Metallurgical": [
        r"metallurgical",
    ],

    "Leather": [
        r"leather",
    ],

    "Plastic": [
        r"plastic",
        r"rubber",
    ],

    "Environmental": [
        r"environmental",
    ],

    "Petrochemical": [
        r"petro chemical",
    ],

    "Safety": [
        r"safety and fire",
    ],

    "Design": [
        r"interior design",
        r"bachelor of design",
    ],
     "Biomedical": [
        r"bio\s*medical"
    ],

    "Geoinformatics": [
        r"geo informatics",
    ],

    "Materials & Metallurgy": [
        r"material science",
        r"metallurgical",
    ],

    "Mining": [
        r"mining",
    ],

    "Architecture & Planning": [
        r"b\.plan",
        r"bplan",
    ],
    "Medical Electronics": [
        r"medical\s+electronics"

    ],
    "VLSI": [
        r"electronics\s+engineering.*vlsi"

    ],
    "Electronics and Telecommunication" : [
        r"electronics\s+and\s+telecommunication"
    ]
}
)

In [ ]:
departments = pd.DataFrame({"canonical_name":department_patterns.keys()})

In [ ]:
departments.values.tolist().index(["Computer"])

0

In [ ]:
def push_department_data():
    departments.to_sql("department",engine,if_exists="append",index=False)

In [ ]:
# push_department_data()

In [ ]:
def normalize_branch_name(name) -> str:
    name: str = str(name).strip().lower()
    name = re.sub(r"\s+", " ", name)
    return name




def classify_departments(branch_name) -> list:
    name: str = normalize_branch_name(branch_name)

    matched_departments: list[dict[int, str]] = []

    for department, patterns in department_patterns.items():
        for pattern in patterns:
            if re.search(pattern, name):
                matched_departments.append({get_dept_index(department):department})
                break 
    return matched_departments if matched_departments else [{-1:"Unlisted"}]

def get_dept_index(dept_name : str):
    return departments.values.tolist().index([dept_name])+1



branches["department"] = (
    branches["branch_name"]
    .apply(classify_departments)
)

In [ ]:
unclassified = branches[
    branches["department"] == "Unlisted"
]["branch_name"].unique()

print("Unclassified:", len(unclassified))
print(unclassified)

Unclassified: 0
<StringArray>
[]
Length: 0, dtype: str

Logic:

Now to push the data into the branch table we need to get the department which it belongs to , so to fetch the department we can use our helper and get the department which the current branch belongs to and thenm we can get the index of it and add 1 solved

In [ ]:
# departments.index+=1
departments

                       canonical_name
0                            Computer
1                          Mechanical
2                                 ECE
3                                 EEE
4                               Civil
5                   AI & Data Science
6                       Biotechnology
7                        Agricultural
8                          Industrial
9                                Food
10                           Chemical
11                          Petroleum
12                  Textile & Fashion
13                           Robotics
14         Production & Manufacturing
15                     Pharmaceutical
16                            Ceramic
17                    Instrumentation
18           Aeronautical & Aerospace
19                           Printing
20                             Marine
21                      Metallurgical
22                            Leather
23                            Plastic
24                      Environmental
25                      Petrochemical
26                             Safety
27                             Design
28                         Biomedical
29                     Geoinformatics
30             Materials & Metallurgy
31                             Mining
32            Architecture & Planning
33                Medical Electronics
34                               VLSI
35  Electronics and Telecommunication

In [ ]:
dept_list = departments.values.tolist()
dept_list

[['Computer'],
 ['Mechanical'],
 ['ECE'],
 ['EEE'],
 ['Civil'],
 ['AI & Data Science'],
 ['Biotechnology'],
 ['Agricultural'],
 ['Industrial'],
 ['Food'],
 ['Chemical'],
 ['Petroleum'],
 ['Textile & Fashion'],
 ['Robotics'],
 ['Production & Manufacturing'],
 ['Pharmaceutical'],
 ['Ceramic'],
 ['Instrumentation'],
 ['Aeronautical & Aerospace'],
 ['Printing'],
 ['Marine'],
 ['Metallurgical'],
 ['Leather'],
 ['Plastic'],
 ['Environmental'],
 ['Petrochemical'],
 ['Safety'],
 ['Design'],
 ['Biomedical'],
 ['Geoinformatics'],
 ['Materials & Metallurgy'],
 ['Mining'],
 ['Architecture & Planning'],
 ['Medical Electronics'],
 ['VLSI'],
 ['Electronics and Telecommunication']]

In [ ]:
branches

,branch_name,department
0,BIO MEDICAL ENGINEERING (SS),[{29: 'Biomedical'}]
1,CIVIL ENGINEERING,[{5: 'Civil'}]
2,COMPUTER SCIENCE AND ENGINEERING (SS),[{1: 'Computer'}]
3,COMPUTER SCIENCE AND ENGINEERING,[{1: 'Computer'}]
4,ELECTRONICS AND COMMUNICATION ENGINEERING,[{3: 'ECE'}]
5,ELECTRICAL AND ELECTRONICS ENGINEERING,[{4: 'EEE'}]
6,ELECTRONICS AND COMMUNICATION ENGINEERING (SS),[{3: 'ECE'}]
7,GEO INFORMATICS,[{30: 'Geoinformatics'}]
8,INDUSTRIAL ENGINEERING,[{9: 'Industrial'}]
9,INFORMATION TECHNOLOGY (SS),[{1: 'Computer'}]
10,MATERIAL SCIENCE AND ENGINEERING (SS),[{31: 'Materials & Metallurgy'}]
11,MECHANICAL ENGINEERING,[{2: 'Mechanical'}]
12,MINING ENGINEERING,[{32: 'Mining'}]
13,MANUFACTURING ENGINEERING,[{15: 'Production & Manufacturing'}]
14,PRINTING TECHNOLOGY,[{20: 'Printing'}]
15,CIVIL ENGINEERING (TAMIL MEDIUM),[{5: 'Civil'}]
16,MECHANICAL ENGINEERING (TAMIL MEDIUM),[{2: 'Mechanical'}]
17,APPAREL TECHNOLOGY (SS),[{13: 'Textile & Fashion'}]
18,CHEMICAL ENGINEERING,[{11: 'Chemical'}]
19,CHEMICAL ENGINEERING (SS),[{11: 'Chemical'}]
20,CERAMIC TECHNOLOGY (SS),[{17: 'Ceramic'}]
21,FOOD TECHNOLOGY (SS),[{10: 'Food'}]
22,INDUSTRIAL BIO TECHNOLOGY,"[{7: 'Biotechnology'}, {9: 'Industrial'}]"
23,INDUSTRIAL BIO TECHNOLOGY (SS),"[{7: 'Biotechnology'}, {9: 'Industrial'}]"
24,LEATHER TECHNOLOGY,[{23: 'Leather'}]
25,PHARMACEUTICAL TECHNOLOGY (SS),[{16: 'Pharmaceutical'}]
26,PETROLEUM ENGINEERING AND TECHNOLOGY (SS),[{12: 'Petroleum'}]
27,TEXTILE TECHNOLOGY,[{13: 'Textile & Fashion'}]
28,AERONAUTICAL ENGINEERING,[{19: 'Aeronautical & Aerospace'}]
29,AUTOMOBILE ENGINEERING,[{2: 'Mechanical'}]
33,ELECTRONICS AND INSTRUMENTATION ENGINEERING,[{18: 'Instrumentation'}]
36,MECHANICAL ENGINEERING (SS),[{2: 'Mechanical'}]
37,PRODUCTION ENGINEERING,[{15: 'Production & Manufacturing'}]
38,RUBBER AND PLASTIC TECHNOLOGY,[{24: 'Plastic'}]
50,INFORMATION TECHNOLOGY,[{1: 'Computer'}]
67,METALLURGICAL ENGINEERING,"[{22: 'Metallurgical'}, {31: 'Materials & Meta..."
100,AUTOMOBILE ENGINEERING (SS),[{2: 'Mechanical'}]
101,BIO TECHNOLOGY (SS),[{7: 'Biotechnology'}]
105,CIVIL ENGINEERING (SS),[{5: 'Civil'}]
109,ELECTRICAL AND ELECTRONICS (SANDWICH) (SS),[{4: 'EEE'}]
110,FASHION TECHNOLOGY (SS),[{13: 'Textile & Fashion'}]
112,INSTRUMENTATION AND CONTROL ENGINEERING (SS),[{18: 'Instrumentation'}]
115,MECHANICAL ENGINEERING (SANDWICH) (SS),[{2: 'Mechanical'}]
117,METALLURGICAL ENGINEERING (SS),"[{22: 'Metallurgical'}, {31: 'Materials & Meta..."
118,PRODUCTION ENGINEERING (SS),[{15: 'Production & Manufacturing'}]
120,PRODUCTION ENGINEERING (SANDWICH) (SS),[{15: 'Production & Manufacturing'}]
121,ROBOTICS AND AUTOMATION (SS),[{14: 'Robotics'}]
122,TEXTILE TECHNOLOGY (SS),[{13: 'Textile & Fashion'}]
124,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE (SS),[{6: 'AI & Data Science'}]
134,ELECTRICAL AND ELECTRONICS ENGINEERING (SS),[{4: 'EEE'}]
142,Computer Science and Business System (SS),[{1: 'Computer'}]
150,MECHATRONICS (SS),[{2: 'Mechanical'}]
152,PLASTIC TECHNOLOGY,[{24: 'Plastic'}]
153,HANDLOOM AND TEXTILE TECHNOLOGY,[{13: 'Textile & Fashion'}]
154,CHEMICAL AND ELECTRO CHEMICAL ENGINEERING (SS),[{11: 'Chemical'}]
179,BIO TECHNOLOGY,[{7: 'Biotechnology'}]
186,PETRO CHEMICAL TECHNOLOGY,"[{11: 'Chemical'}, {12: 'Petroleum'}, {26: 'Pe..."
187,PHARMACEUTICAL TECHNOLOGY,[{16: 'Pharmaceutical'}]
255,COMPUTER SCIENCE AND ENGINEERING (AI AND MACHI...,[{1: 'Computer'}]
257,COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE),"[{1: 'Computer'}, {6: 'AI & Data Science'}]"
260,CIVIL AND STRUCTUTURAL ENGINEERING,[{5: 'Civil'}]
266,MECHANICAL ENGINEERING (MANUFACTURING),"[{2: 'Mechanical'}, {15: 'Production & Manufac..."
284,FOOD TECHNOLOGY,[{10: 'Food'}]
286,Artificial Intelligence and Data Science,[{6: 'AI & Data Science'}]
293,Mechatronics Engineering,[{2: 'Mechanical'}]
294,Artificial Intelligence and Machine Learning,[{6: 'AI & Data Science'}]
295,COMPUTER SCIENCE AND BUSSINESS SYSTEM,[{1: 'Computer'}]
301,COMPUTER SCIENCE AND DESIGN,[{1: 'Computer'}]
324,BIO MEDICAL ENGINEERING,[{29: 'Biomedical'}]
353,MARINE ENGINEERING,[{21: 'Marine'}]
361,AGRICULTURE ENGINEERING,[{8: 'Agricultural'}]
365,ROBOTICS AND AUTOMATION,[{14: 'Robotics'}]
431,COMPUTER AND COMMUNICATION ENGINEERING,[{1: 'Computer'}]
460,PETROLEUM ENGINEERING,[{12: 'Petroleum'}]
472,MEDICAL ELECTRONICS ENGINEERING,[{34: 'Medical Electronics'}]
483,MECHANICAL ENGINEERING (SANDWICH),[{2: 'Mechanical'}]
484,MECHANICAL AND AUTOMATION ENGINEERING,[{2: 'Mechanical'}]
636,AEROSPACE ENGINEERING,[{19: 'Aeronautical & Aerospace'}]
642,FASHION TECHNOLOGY,[{13: 'Textile & Fashion'}]
811,M.Tech. Computer Science and Engineering (Inte...,[{1: 'Computer'}]
816,INSTRUMENTATION AND CONTROL ENGINEERING,[{18: 'Instrumentation'}]
834,Cyber Security,[{1: 'Computer'}]
1098,COMPUTER SCIENCE AND ENGINEERING (TAMIL),[{1: 'Computer'}]
1240,PHARMACEUTICAL ENGINEERING,[{16: 'Pharmaceutical'}]
1264,MECHATRONICS,[{2: 'Mechanical'}]
1280,Safety and Fire Engineering,[{27: 'Safety'}]
1289,TEXTILE CHEMISTRY,[{13: 'Textile & Fashion'}]
1312,Computer Science and Technology,[{1: 'Computer'}]
1533,COMPUTER TECHNOLOGY,[{1: 'Computer'}]
1542,Information Science and Engineering,[{1: 'Computer'}]
1602,ELECTRONICS AND TELECOMMUNICATION ENGINEERING,"[{3: 'ECE'}, {36: 'Electronics and Telecommuni..."
1605,Computer Science and Engineering (Cyber Security),[{1: 'Computer'}]
1759,PETRO CHEMICAL ENGINEERING,"[{11: 'Chemical'}, {12: 'Petroleum'}, {26: 'Pe..."
1778,Mechanical and Mechatronics Engineering (Addit...,"[{2: 'Mechanical'}, {15: 'Production & Manufac..."
1779,Computer Science and Engineering (Internet of ...,[{1: 'Computer'}]
1927,ENVIRONMENTAL ENGINEERING,[{25: 'Environmental'}]
1930,Bio Technology and Bio Chemical Engineering,"[{7: 'Biotechnology'}, {11: 'Chemical'}]"
2434,INDUSTRIAL ENGINEERING AND MANAGEMENT,[{9: 'Industrial'}]
14,PRINTING AND PACKING TECHNOLOGY,[{20: 'Printing'}]
28,B.Plan,[{33: 'Architecture & Planning'}]
106,Computer Science and Engineering (Artificial I...,"[{1: 'Computer'}, {6: 'AI & Data Science'}]"
177,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,[{6: 'AI & Data Science'}]
258,COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL I...,"[{1: 'Computer'}, {6: 'AI & Data Science'}]"
381,AGRICULTURAL ENGINEERING,[{8: 'Agricultural'}]
498,Computer Science and Engineering (Internet of ...,[{1: 'Computer'}]
309,Electronics and Communication ( Advanced Commu...,[{3: 'ECE'}]
312,Electronics Engineering (VLSI design and Techn...,[{35: 'VLSI'}]
6,Electronics Engineering (VLSI Design and Techn...,[{35: 'VLSI'}]
15,PRINTING & PACKING TECHNOLOGY,[{20: 'Printing'}]
152,Interior Design (SS),[{28: 'Design'}]
184,Electronics Engineering (VLSI Design and Techn...,[{35: 'VLSI'}]
190,Civil Engineering (Environmental Engineering),"[{5: 'Civil'}, {25: 'Environmental'}]"
194,Electrical and Computer Engineering,"[{1: 'Computer'}, {4: 'EEE'}]"
197,Mechanical Engineering (Automobile),[{2: 'Mechanical'}]
199,Mechanical and Smart Manufacturing,"[{2: 'Mechanical'}, {15: 'Production & Manufac..."
334,Electronics and Communication (Advanced Commun...,[{3: 'ECE'}]
412,MEDICAL ELECTRONICS,[{34: 'Medical Electronics'}]
883,Bachelor of Design,[{28: 'Design'}]
993,Electronic Instrumentation and Control Enginee...,"[{4: 'EEE'}, {18: 'Instrumentation'}]"
1590,Electronics and Computer Engineering,"[{1: 'Computer'}, {3: 'ECE'}]"
2464,Civil Engineering,[{5: 'Civil'}]
2465,Computer Science and Engineering,[{1: 'Computer'}]
2466,Electrical and Electronics Engineering,[{4: 'EEE'}]
2467,Mechanical Engineering,[{2: 'Mechanical'}]
835,ENVIRONMENTAL SCIENCE & TECHNOLOGY,[{25: 'Environmental'}]
839,ROBOTICS AND ARTIFICIAL INTELLIGENCE,"[{6: 'AI & Data Science'}, {14: 'Robotics'}]"
1138,COMPUTER SCIENCE AND ENGINEERING(ARTIFICIAL IN...,"[{1: 'Computer'}, {6: 'AI & Data Science'}]"
1408,Interior Design,[{28: 'Design'}]

In [ ]:
branches_data = df[["branch_code","branch_name",]]

In [ ]:
result = conn.exec_driver_sql("SELECT * FROM college WHERE name LIKE %s",("Kongu E%",))

In [ ]:
result.all()

[(241, 'SELF FINANCING COLLEGES TIER 1', 2711, 'ERODE', 'Kongu Engineering College (Autonomous), Perundurai, Erode District 638052', None, None, None, 'PRIVATE', 'TIER 1'),
 (720, 'SELF FINANCING COLLEGES TIER 1', 2711, 'ERODE', 'Kongu Engineering College (Autonomous)  Perundurai  Erode District 638052', None, None, None, 'PRIVATE', 'TIER 1'),
 (1122, 'SELF FINANCING COLLEGES TIER 1', 2711, 'ERODE', 'Kongu Engineering College (Autonomous), Perundurai Railway Station Road,Thoppupalayam,Perundurai, Erode-638052.', None, None, None, 'PRIVATE', 'TIER 1')]

In [ ]:
conn.exec_driver_sql("SELECT COUNT(*) FROM college").all()

[(1359,)]